In [1]:
import cv2
import mediapipe as mp
import numpy as np

In [9]:
mp_pose = mp.solutions.pose
mp_draw = mp.solutions.drawing_utils
pose = mp_pose.Pose()

In [80]:
def get_video_keypoints(path='../sample.mp4', discard_points=(1, 2, 3, 4, 5, 6, 9, 10, 21, 22)):
    cap = cv2.VideoCapture(path)
    keypoints = []
    originals = []
    while(cap.isOpened()):
        _, img = cap.read()    
        if (img is None):
            break
        keypoint = []
        img_RGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        result = pose.process(img_RGB)
        if result.pose_landmarks:
            # mp_draw.draw_landmarks(img, result.pose_landmarks, mp_pose.POSE_CONNECTIONS)
            for id, lm in enumerate(result.pose_landmarks.landmark):
                if id in discard_points:
                    continue
                height, width, channel = img.shape
                # cx, cy = int(lm.x * width), int(lm.y * height)
                # cv2.circle(img, (cx, cy), 5, (255, 0, 0), cv2.FILLED)
                # normalize pkeypoints (value range between -1 and 1)
                keypoint.append(lm.x * 2 - 1)
                keypoint.append(lm.y * 2 - 1)
                keypoint.append(lm.z)
            keypoints.append(keypoint)   
            originals.append(result.pose_landmarks)
        else:
            keypoints.append(keypoints[-1])  
            originals.append(originals[-1])
        # cv2.imshow('frame',img)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

    keypoints = np.array(keypoints) # convert into numpy array

    return keypoints, originals

In [81]:
keypoints, originals = get_video_keypoints()

In [72]:
keypoints.shape

(719, 69)

In [73]:
sum(keypoints < -1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [82]:
keypoints2, originals2 = get_video_keypoints('https://aistdancedb.ongaaccel.jp/v1.0.0/video/10M/gBR_sBM_c01_d04_mBR0_ch01.mp4')

In [75]:
keypoints2.shape

(719, 69)

In [76]:
mat = keypoints == keypoints2

In [77]:
np.sum(mat)

20

In [78]:
keypoints[1]

array([ 0.00527072, -0.10486776, -0.18386245,  0.01527131, -0.10769051,
       -0.09463866, -0.02037013, -0.12617421, -0.1205324 ,  0.01934493,
        0.00402546, -0.03921313, -0.06964082, -0.06389654, -0.08373426,
        0.07087052,  0.05081069, -0.01832885, -0.1454615 , -0.0881809 ,
       -0.09199469,  0.1352421 ,  0.01395321, -0.0809948 , -0.21580088,
       -0.1448276 , -0.14200434,  0.15756679,  0.00143051, -0.09079603,
       -0.23626292, -0.15629983, -0.15623783,  0.15630841, -0.01503408,
       -0.10820089, -0.236844  , -0.16273367, -0.17070948, -0.02555144,
        0.25303531,  0.01584669, -0.07925349,  0.24135029, -0.01583396,
       -0.04079384,  0.44368744, -0.07045238, -0.07647157,  0.43680596,
       -0.00443262, -0.07729697,  0.61289656,  0.05600936, -0.04991513,
        0.54329872,  0.18439208, -0.09189826,  0.63895023,  0.06589296,
       -0.03995109,  0.5437417 ,  0.20324703, -0.06108105,  0.68296325,
        0.01569803, -0.05513036,  0.60920501,  0.17122117])

In [79]:
keypoints2[1]

array([ 0.00498664, -0.10517204, -0.18373416,  0.0152266 , -0.10772967,
       -0.0951362 , -0.02030432, -0.12624997, -0.12038045,  0.01953256,
        0.00424147, -0.04025197, -0.0696137 , -0.06348073, -0.08318171,
        0.07051289,  0.05067253, -0.02068449, -0.14543718, -0.08794147,
       -0.09086286,  0.1351124 ,  0.01417255, -0.08823098, -0.21584445,
       -0.14474618, -0.14077954,  0.157511  ,  0.00178337, -0.09862226,
       -0.23627764, -0.15626466, -0.15469123,  0.15622568, -0.01475334,
       -0.11574039, -0.23692548, -0.16272426, -0.16676387, -0.02559197,
        0.253075  ,  0.0155296 , -0.07933134,  0.24123192, -0.01551647,
       -0.04090911,  0.44391894, -0.06607189, -0.07643878,  0.43691361,
       -0.00352544, -0.07711011,  0.6127454 ,  0.05507562, -0.04978758,
        0.54332232,  0.18415114, -0.0916906 ,  0.63878572,  0.06501646,
       -0.03988653,  0.54362762,  0.20297927, -0.06101781,  0.68274176,
        0.01456887, -0.0551675 ,  0.61092222,  0.17091037])

In [83]:
cap = cv2.VideoCapture('../sample.mp4')
i = 0
while(cap.isOpened()):
    ret, img = cap.read()    
    if (img is None):
            break
    
    img_RGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    mp_draw.draw_landmarks(img, originals[i], mp_pose.POSE_CONNECTIONS)  
    mp_draw.draw_landmarks(img, originals2[i], mp_pose.POSE_CONNECTIONS)  

    cv2.imshow('frame',img)
    i += 1
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 